name: tests
on: push
jobs:
  run tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm run test
      - name: upload coverag reports
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
